name: PanIndex Release
on:
  release:
    types: [created]
jobs:
  xgo:
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.14.3
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: build
          prefix: myapp
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: PanIndex.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}